@jwt = eyJhbGciOiJIUzI1NiJ9.eyJkal9pZCI6MiwiZXhwIjoxNjM0NDk0NTI1fQ.zAzA1U-vefuCEc3UP8ekqVLFFJsuFj0jM1BMbPwvNsU
@hostname = http://localhost:3000

######################################### DJS

### DJs create (signup)
POST {{hostname}}/djs
Authorization: Bearer {{jwt}}
Content-Type: application/json

  {
    "name": "New DJ",
    "email": "dj@dj.com",
    "password": "dj",
    "password_confirmation": "dj"
  }

### DJs show
GET http://localhost:3000/djs/2

### DJs update

PATCH {{hostname}}/djs/4
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Casey Rells",
  "email": "emailcaseyrells@gmail.com",
  "info": "",
  "website": "www.caseyrells.com",
  "image_url": "", 
  "instagram": "@caseyrells", 
  "twitter": "",
  "facebook": "",
  "venmo": "",
  "cashapp": "",
  "paypal": ""
}

### DJ destroy

DELETE {{hostname}}/djs/1

#################################### REQUESTS

### Requests Index

GET {{hostname}}/requests


### Request create
POST {{hostname}}/requests
Content-Type: application/json

  {
    "song": "A Milli by Lil Wayne",
    "comments": "Thank you!"
  }

### Requests update

PATCH {{hostname}}/requests/4
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "status": "approved"
}

### Requests destroy

DELETE {{hostname}}/requests/4





#################################### SESSIONS

### Sessions create (login)

POST {{hostname}}/sessions
Content-Type: application/json

  {
    "email": "test@test.com",
    "password": "test"
  }