@jwt = eyJhbGciOiJIUzI1NiJ9.eyJkal9pZCI6MiwiZXhwIjoxNjM0NDk0NTI1fQ.zAzA1U-vefuCEc3UP8ekqVLFFJsuFj0jM1BMbPwvNsU
@hostname = http://localhost:3000

### DJ create (signup)
POST {{hostname}}/djs
Authorization: Bearer {{jwt}}
Content-Type: application/json

  {
    "name": "New DJ",
    "email": "dj@dj.com",
    "password": "dj",
    "password_confirmation": "dj"
  }

### DJ show
GET http://localhost:3000/djs/2

### DJ update

### DJ destroy










### Sessions create (login)

POST {{hostname}}/sessions
Content-Type: application/json

  {
    "email": "test@test.com",
    "password": "test"
  }