@jwt = eyJhbGciOiJIUzI1NiJ9.eyJkal9pZCI6MywiZXhwIjoxNjM1MDEyMzI0fQ.Yy3wkQdcXFlA38LQk-LRfbj1W-o78fum3yYgcvqb4eU
@hostname = http://localhost:3000

######################################### DJS

### DJs create (signup)
POST {{hostname}}/djs
Content-Type: application/json

  {
    "name": "test",
    "email": "test2@test.com",
    "password": "test",
    "password_confirmation": "test"
  }

### DJs show
GET http://localhost:3000/djs/11

### DJs update

PATCH {{hostname}}/djs/11
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "test",
  "email": "test",
  "info": "test",
  "website": "www.test.com",
  "image_url": "test", 
  "instagram": "test", 
  "twitter": "test",
  "facebook": "test",
  "venmo": "test",
  "cashapp": "test",
  "paypal": "test"
}

### DJ destroy

DELETE {{hostname}}/djs/9

#################################### REQUESTS

### Requests Index

GET {{hostname}}/requests


### Request create
POST {{hostname}}/requests
Content-Type: application/json

  {
    "song": "A Milli by Lil Wayne",
    "comments": "Thank you!",
    "dj_id": 4
  }

### Requests update

PATCH {{hostname}}/requests/2
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "status": "declined"
}

### Requests destroy

DELETE {{hostname}}/requests/6


#################################### SESSIONS

### Sessions create (login)

POST {{hostname}}/sessions
Content-Type: application/json

  {
    "email": "casey@casey.com",
    "password": "casey"
  }

#################################### QR code request

GET http://api.qrserver.com/v1/create-qr-code/?data=www.caseycantrell.com&size=500x500&margin=20&bgcolor=00f&color=fff&ecc=H